# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: piráti, česká pirátská strana, svoboda, demokracie, kontrola moci a mocných, zjednodušení státu pomocí technologií, ochranu občanů před šikanou, obranu svobody, černá na bílé, ivan bartoš, e-government, politika pro 21. století # dobré keywords jsou ty co lidé piší do googlu když hledají naši stránku
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

theme: jekyll-theme-pirati

sass:
  style: compressed
  sass_dir: _sass

organization:
  name: Jmeno skupiny používající web - př Pirástá strana
  shortName: Název skupiny
  contactUid: jakub.pirat
  email: example@pirati.cz
  phone: +420 777 123 456 789
  address: |
    Piratská planeta 1
    100 00 Pirátsko
  residenceImg:
  mapLink: https://mapy.cz/zakladni?base=ophoto&q=Radou%C5%A1ova%2014,%20Chrudim
  redmineLink: https://redmine.pirati.cz/projects

homepageBanner:
  display: false
  link: /komunalni-volby/
  title: Komunální volby 2018
  breakpoint: 640 # breakpoint in pixels when to start showing `default` instead of `mobile`
  image:
    default: path/to/img.jpg
    mobile: path/to/img.jpg

calendar:
  # Get api key from Google Developer Console
  apiKey:
  title: Celostátní kalendář
  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=nk73m1m89vhf5g2vojp6tnqe58%40group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3

facebook:
  loadSDK: true
  profilePage:
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/jekyll-theme-pirati/
  branch: master

# Image banner on the top of the homepage. Useful for promoting current events.
homepageBanner:
  display: false
  link: /komunalni-volby/
  title: Komunální volby 2018
  breakpoint: 640 # breakpoint in pixels when to start showing `default` instead of `mobile`
  image:
    default: filename.jpg #obrazek vložte do assets/img
    mobile: filename.jpg #obrazek vložte do assets/img


# Build settings
markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /program/:path/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "people, foto, personContact"
  -
    scope:
      path: "_program"
    values:
      layout: "page"
      rbar: "garant, program"

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-3.5.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
