# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Piráti Turnov
email: pirati-turnov@pirati.cz
description: >- # this means to ignore newlines until "baseurl:"
  Piráti Turnov
keywords: piráti, turnov, česká pirátská strana, svoboda, demokracie, kontrola moci a mocných, zjednodušení státu pomocí technologií, ochranu občanů před šikanou, obranu svobody,  e-government, politika pro 21. století # dobré keywords jsou ty co lidé piší do googlu když hledají naši stránku
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

theme: jekyll-theme-pirati

sass:
  style: compressed
  sass_dir: _sass

administrator:
  email: marek.forster@pirati.cz # mail kam pujdou chybove vystupy


organization:
  name: Piráti Turnov
  shortName: Piráti Turnov
  contactUid: david.schindler
  email: david.schindler@pirati.cz
  phone: +420 605 168 581
  address: |
    PIXEL - Pirátské centrum libereckého kraje
    Generála Mrázka 413/4 
    468 01 Jablonec nad Nisou
  #residenceImg:
  mapLink: https://mapy.cz/zakladni?x=15.1709248&y=50.7244738&z=18&source=firm&id=12829995
  redmineLink: https://redmine.pirati.cz/projects

homepageBanner:
  display: true
  link: /komunalni-volby/
  title: Komunální volby 2018
  breakpoint: 640 # breakpoint in pixels when to start showing `default` instead of `mobile`
  image:
    default: banner-default.jpg
    mobile: banner-mobile.jpg

calendar:
  # Get api key from Google Developer Console
  apiKey:
  title: Celostátní kalendář
  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=nk73m1m89vhf5g2vojp6tnqe58%40group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3

facebook:
  loadSDK: true
  profilePage: https://www.facebook.com/pirati.turnov/
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratiLiK

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/jekyll-theme-pirati/
  branch: master

# Build settings
markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/

  program:
    output: true
    permalink: /komunalni-volby/program/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar: "people, foto, personContact"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar: "garant, program"

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.4.0/gems/jekyll-theme-pirati-6.6.1/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
